### ISSUE TITLE
Setting context to an Oracle provider with FN_API_URL set still prompts for private key phrase

### ISSUE THREAD

**Issue by JadeRedworth** [fnproject/cli#249]
When 'current-context' is set to an Oracle provider, but `FN_API_URL` is set (and therefore overrides api-url in the context file) users are still prompted for the password keyphrase for their OCI private key. 

Example:
```
FN_API_URL=http://localhost:8080/v1
current-context=oracle
```

The command `fn apps l` will ask for the oracle password becuase that is the current-context but show apps based on `FN_API_URL`.

**Comment by mantree** [comment]
This will go both ways as well: context:default, FN_API_URL=some-provider-url, with fail due to the auth headers not being created.

Provider specific headers are created based on the configured 'provider' value. We could change to url inspection for the decision, but I don't really think that's the way to go.

**Comment by rikgibson** [comment]
I wonder whether we should rethink the "context vs env vars" thing.  Instead of allowing env vars to override values set in the context, maybe it should be a context-or-env model - so if you have no context set then you can use the env vars, but if you do have a context set then the env vars are ignored.

**Comment by JadeRedworth** [comment]
I _believe_ with the changes from `Move SDK providers to Go SDK, remove from CLI` [#298](https://github.com/fnproject/cli/pull/298) we no longer prompt for a password for OCI credentials. Will confirm if this is the case, if so this bug is no longer an issue.

**Comment by zootalures** [comment]
I'm pretty sure we fixed this, closing.
