### ISSUE TITLE
add --tail to fn logs

### ISSUE THREAD

**Issue by carimura** [fnproject/cli#35]
similar too `heroku logs --tail` ..

would work for both functions and apps (as apps functionality gets released)

**Comment by carimura** [comment]
bump. need. 

`fn logs g myapp myfunc --tail`

**Comment by josephholsten** [comment]
Looks like `heroku logs` [accesses their resource](https://github.com/heroku/cli/blob/master/packages/run-v5/lib/log_displayer.js#L37) as an [event-stream](https://html.spec.whatwg.org/multipage/server-sent-events.html), but the `fn log` uses [GetCallLogs](https://github.com/fnproject/cli/blob/master/objects/log/logs.go#L58) which to access [handleCallLogGet](https://github.com/fnproject/fn/blob/master/api/server/call_logs.go#L37), which seems to respond with the current log instead of a longpoll event stream. 

Seems like this isn't a good first issue unless you have an idea about how to implement this that isn't obvious.
