### ISSUE TITLE
Specify templates for `fn init --runtime=.....` outside of the CLI source code

### ISSUE THREAD

**Issue by mjg123** [fnproject/cli#356]
As a function developer I want to specify my own template when creating a new function so that I can provide reduce the amount of boilerplate updating.
As an FDK developer I want to not have my FDK coupled to the CLI by the hard-coded project templates in the CLI.

Strawman suggestion for how this could work:

  - Have each supported runtime use an "init-image" that the CLI pulls and invokes when generating a new function.
  - User can specify a different "--init-image=<image>" to plug in their own boilerplate.
  - The contract for images is to run with some arguments such as `function-name` (and which others?) and to stream out a tarball of the function template, which the CLI can put in place on disk. The alternative of mounting the directory in is risky because of the difficulty in reliably determining the correct user.

**Comment by shaunsmith** [comment]
I have previously suggested a configurable Docker image based system with a defined contract between CLI and image so any number of files could be return as part of the template.  @rikgibson did we capture this as issues or just in meeting notes?

**Comment by rikgibson** [comment]
Hey @shaunsmith I captured the overall concept as a JIRA, which is where this issue ultimately spawned from. We didn't really get into the nitty gritty though - what's the contract, online vs offline experience, breadth of language support etc.  I'd also like to see the build and run images built by the FDK (I think the Java FDK images already are) and the values of build_image and run_image in func.yaml populated by the FDK based on params supplied to `fn init`, rather than baking into CLI.

**Comment by rikgibson** [comment]
Possible params to configure the boilerplate, other than `function-name` - `class-name`, `language-version`? Others? `language-version` may or may not entail different boilerplate, certainly different build/run images.

**Comment by mjg123** [comment]
I'll prototype this and see what I find.

**Comment by shaunsmith** [comment]
We should also think beyond language and support arbitrary init/build/run images so that a team could define a template that matches their project needs or corporate standards, for example.  I had envisioned the CLI supporting registration of "runtimes" which is maintained in the `.fn/config.yaml` with defaults for supported runtimes.
