### ISSUE TITLE
[feature][ux] generate boilerplate per func.yml

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#371]
At this particular moment, CLI would fail if `func.yml` exists in the folder.

As a developer, I'd like to set up my own `func.yml` and ask CLI to generate a boilerplate with respect to what's going to be mentioned in `func.yml`:

- if the runtime set to any of supported langs the CLI must generate the boilerplate

- if the runtime set to `docker` then CLI must create an empty Dockerfile

- if no runtime specified, abort.

- if the boilerplate files already in a folder, abort

CLI interface:

`fn init --from-func-file=func.yml` to generate boilerplate

`fn init --from-func-file=func.yml --force` to regenerate boilerplate

**Comment by mjg123** [comment]
Hi I have some questions about this:

1/ Who is it for? I think most users would want to start from either: (a) some working code or (b) a blank slate, but who is it outside of a small subset of our dev team that *starts* by writing out a `func.yaml`?

2/ How is this different from `mv func.yaml /tmp && fn init --runtime=blah && mv /tmp/func.yaml .` ?  How would we justify the maintenance and testing burden for it?

3/ Generally I think the CLI already has too much runtime-specific code in it.  The proposal for init-images at #369 seems like a sensible way to reduce it but it's not clear how that works with this proposal.

**Comment by mjg123** [comment]
OK I'll wait for other people's opinions on 1&2 too.

Specifically the problem I can see for point 3 is that the name of the entrypoint method is in `func.yaml` for Java/Kotlin/SVM runtimes, so presumably the generated code would have to match whatever the user has put in `func.yaml`. This means passing the entrypoint into the boilerplate-generator and some logic to make that entrypoint exist as a real method. Then if that value is absent, or doesn't represent a valid method name the boilerplate-generator will have to fail somehow which gives more responsibility to the boilerplate-generator.

So this is already more complexity than the LangHelpers support atm - and I'd really like to simplify them and decouple them from the CLI (see #380).

**Comment by mjg123** [comment]
Looking in more detail there is a lot that can be put in func.yaml which can't be guaranteed to turn into a working function.  Tests, {build,run}_image, triggers, etc.  I don't see how we can make this feature so that it doesn't trip people up by creating functions that can't be built or won't work at runtime.  Given that there's no clear customer requirement and an easy workaround exists I'm not sure why we would add this.

**Comment by rdallman** [comment]
of the bullet points given for behavior changes here, the only one that seems remotely useful is:

> if the runtime set to any of supported langs the CLI must generate the boilerplate

is our boilerplate all that useful? this would complicate the behavior of init and maybe the expectations for users. for users that are familiar enough with fn, after writing a `func.yaml` file it seems likely they're familiar enough to be able to import the fdk and write the event loop handler. 

there are some pitfalls in trying to analyze the code itself for our fdk specific event loop [in every supported lang], it won't be perfect without using static analysis tools (grep would probably cover 90%, but there's a little window), and may not be immediately apparent 'why didn't fn init work' to users if they expect certain behavior. e.g. i could see a user making a `func.py` file, since that's the default we generate, we could override that for some reason if our analyzer doesn't get a hit, and users will get mad. obviously we could avoid this specific example, i guess my point is that there are some catches here and cases to handle, where the expectations of any given user aren't clear.

> 1/ Who is it for? I think most users would want to start from either: (a) some working code or (b) a blank slate, but who is it outside of a small subset of our dev team that starts by writing out a func.yaml?

I agree with this analysis. in general it seems much easier to cover this use case by proposing that a user interested in this behavior type `fn init` before creating a `func.yaml` file, since they're typing the runtime in the `func.yaml`, it shouldn't be too much of a cognitive burden to type `fn init --runtime python` before marking up the `func.yaml` file with all the fields they want instead of typing out the flags. are there additional pitfalls here I'm missing?

in general, I think we should really strongly promote one or as few as possible work flows and encourage users to bend to these instead of trying to adapt to every possible work flow a user could come up with -- though it's nice to see maybe we could make things slightly more intuitive or easy, this proposal itself doesn't seem like it covers very many users and is easy to work around (agree with @mjg123), additionally the workflow itself doesn't seem all that more convenient than the proposed workaround(s) and is simply a matter of preference to not type cli flags(?). should we make stronger suggestions in our error message when a `func.yaml` with useful steps to take to resolve?
