### ISSUE TITLE
fn deploy --local now expects registry to be set

### ISSUE THREAD

**Issue by zootalures** [fnproject/cli#393]
It used to be the case that `fn deploy --local` ignored the absence of a configured registry - as of recently this is no longer the case

```bash
 fn deploy --local  --app foo                                                    1
Deploying sac-java-t-fn to app: foo
Bumped to version 0.0.6
Building image sac-java-t-fn:0.0.6
Updating function sac-java-t-fn using image sac-java-t-fn:0.0.6...

Fn: image name must have a dockerhub owner or private registry. Be sure to set FN_REGISTRY env var, pass in --registry or configure your context file

See 'fn <command> --help' for more information. Client version: 0.4.150

```

**Comment by rikgibson** [comment]
I wonder if it's time, for a new local Fn install, to populate the initial `default` context with a simple `local` value for the `REGISTRY` field, and have the `default` context selected OOTB. Then we're usable for local development right off the bat without having to document any further config steps or populating env vars.

Having said that, even the tutorials say to populate FN_REGISTRY with a value of `fndemouser` when just doing local deployments.

**Comment by rikgibson** [comment]
Also pondering whether `--local` might be better rephrased as `--no-push`?

**Comment by rdallman** [comment]
we could delay it until a user types `fn deploy` for real without `--local` but it's not a great ux since it will just blow up later. fwiw i was wrestling with this the other day, as well, and was not a fan of dealing with the registry business in any capacity, and it took me a minute to figure it out (I have old man river I've worked on this too long bias, but still). i've always found FN_REGISTRY really strange. from what i can tell it exists solely so that people can clone tutorials and push `fn deploy` with _their_ fn registry set instead of having to rename the images all over, which i get, i'm just having a hard time coping with it being the preferred direction to push users. many users on a team for instance will be pushing to their company's docker registry and can code all the names in. i've personally never used it either and preferred to hardcode `fnproject/xxx` or `rdallman/xxx`. the demo clone use case while important seems not the primary use case, at least. there's my $.02 (calling for murder), sorry if tangential

**Comment by zootalures** [comment]
This issue was fundamentally fixed by https://github.com/fnproject/cli/pull/403
