### ISSUE TITLE
'fn migrate' should update the format to 'http-stream'

### ISSUE THREAD

**Issue by delabassee** [fnproject/cli#457]
Given that formats will be deprecated in favour of `http-stream`, is there still a valid reason to keep the `format` entry in `func.yaml`?
If so, `fn migrate`should update the format to `http-stream`.

**Comment by denismakogon** [comment]
Format still a part of functions API, so, that’s said, it’ll go away once a server would drop that field as well.

**Comment by rikgibson** [comment]
No answer your first question @delabassee, no there isn't a valid reason to keep the `format` entry in `func.yaml`. We just need to complete the work to be fully `http-stream` only across the board, at which point it can be removed.  `fn migrate` should then migrate older functions to a newer `func/yaml` schema version that removes `format` rather than changing it.

So going to close this I think.

**Comment by shaunsmith** [comment]
@rikgibson which issue is tracking the removal of `format` from `func.yaml`?

**Comment by rdallman** [comment]
@shaunsmith @rikgibson  https://github.com/fnproject/cli/pull/542
